HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Compile;RootName:HC85
Implementation;Compile||(null)||Please refer to the log file for details about 1 Info(s)||HC85_compile_log.rpt;liberoaction://open_report/file/HC85_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:HC85
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||HC85_placeroute_log.rpt;liberoaction://open_report/file/HC85_placeroute_log.rpt||(null);(null)
