Implementation;Compile;RootName:encoder8_3_1
Implementation;Compile||(null)||Please refer to the log file for details about 1 Info(s)||encoder8_3_1_compile_log.rpt;liberoaction://open_report/file/encoder8_3_1_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:encoder8_3_1
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||encoder8_3_1_placeroute_log.rpt;liberoaction://open_report/file/encoder8_3_1_placeroute_log.rpt||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
