HelpInfo,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.9\SynplifyPro\bin\mbin\assistant
Implementation;Compile;RootName:HC194
Implementation;Compile||(null)||Please refer to the log file for details about 1 Warning(s)||HC194_compile_log.rpt;liberoaction://open_report/file/HC194_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:HC194
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||HC194_placeroute_log.rpt;liberoaction://open_report/file/HC194_placeroute_log.rpt||(null);(null)
